DO
$$
BEGIN
   IF NOT EXISTS (
      SELECT
      FROM pg_catalog.pg_roles
      WHERE rolname = 'ebookmaker_app'
   ) THEN
      CREATE ROLE ebookmaker_app LOGIN PASSWORD 'ebookmaker_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
   END IF;
END
$$;

GRANT CONNECT ON DATABASE ebookmaker TO ebookmaker_app;
GRANT USAGE, CREATE ON SCHEMA public TO ebookmaker_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ebookmaker_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ebookmaker_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ebookmaker_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO ebookmaker_app;
